// Auto-generated file - DO NOT EDIT
// Use `tools/instruction-codegen` to edit

/// Metadata for a single CPU instruction
#[derive(Clone)]
pub struct InstructionMeta {
    pub mnemonic: &'static str,
    pub opcode: u8,
    pub bytes: u8,
    pub cycles: u8,
}

pub const UNPREFIXED_INSTRUCTIONS: [InstructionMeta; 256] = [
    // 0x00-0x0F
    InstructionMeta {
        mnemonic: "NOP",
        opcode: 0x00,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x01,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x02,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x03,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x04,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x05,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x06,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RLCA",
        opcode: 0x07,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x08,
        bytes: 3,
        cycles: 20,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x09,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x0A,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x0B,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x0C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x0D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x0E,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRCA",
        opcode: 0x0F,
        bytes: 1,
        cycles: 4,
    },
    // 0x10-0x1F
    InstructionMeta {
        mnemonic: "STOP",
        opcode: 0x10,
        bytes: 2,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x11,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x12,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x13,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x14,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x15,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x16,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RLA",
        opcode: 0x17,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "JR",
        opcode: 0x18,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x19,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x1A,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x1B,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x1C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x1D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x1E,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRA",
        opcode: 0x1F,
        bytes: 1,
        cycles: 4,
    },
    // 0x20-0x2F
    InstructionMeta {
        mnemonic: "JR",
        opcode: 0x20,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x21,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x22,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x23,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x24,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x25,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x26,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "DAA",
        opcode: 0x27,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "JR",
        opcode: 0x28,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x29,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x2A,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x2B,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x2C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x2D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x2E,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "CPL",
        opcode: 0x2F,
        bytes: 1,
        cycles: 4,
    },
    // 0x30-0x3F
    InstructionMeta {
        mnemonic: "JR",
        opcode: 0x30,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x31,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x32,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x33,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x34,
        bytes: 1,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x35,
        bytes: 1,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x36,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "SCF",
        opcode: 0x37,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "JR",
        opcode: 0x38,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x39,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x3A,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x3B,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "INC",
        opcode: 0x3C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "DEC",
        opcode: 0x3D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x3E,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "CCF",
        opcode: 0x3F,
        bytes: 1,
        cycles: 4,
    },
    // 0x40-0x4F
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x40,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x41,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x42,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x43,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x44,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x45,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x46,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x47,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x48,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x49,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x4A,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x4B,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x4C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x4D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x4E,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x4F,
        bytes: 1,
        cycles: 4,
    },
    // 0x50-0x5F
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x50,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x51,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x52,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x53,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x54,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x55,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x56,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x57,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x58,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x59,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x5A,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x5B,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x5C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x5D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x5E,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x5F,
        bytes: 1,
        cycles: 4,
    },
    // 0x60-0x6F
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x60,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x61,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x62,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x63,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x64,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x65,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x66,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x67,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x68,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x69,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x6A,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x6B,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x6C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x6D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x6E,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x6F,
        bytes: 1,
        cycles: 4,
    },
    // 0x70-0x7F
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x70,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x71,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x72,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x73,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x74,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x75,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "HALT",
        opcode: 0x76,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x77,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x78,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x79,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x7A,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x7B,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x7C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x7D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x7E,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0x7F,
        bytes: 1,
        cycles: 4,
    },
    // 0x80-0x8F
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x80,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x81,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x82,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x83,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x84,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x85,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x86,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0x87,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0x88,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0x89,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0x8A,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0x8B,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0x8C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0x8D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0x8E,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0x8F,
        bytes: 1,
        cycles: 4,
    },
    // 0x90-0x9F
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0x90,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0x91,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0x92,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0x93,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0x94,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0x95,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0x96,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0x97,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0x98,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0x99,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0x9A,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0x9B,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0x9C,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0x9D,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0x9E,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0x9F,
        bytes: 1,
        cycles: 4,
    },
    // 0xA0-0xAF
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xA0,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xA1,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xA2,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xA3,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xA4,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xA5,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xA6,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xA7,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xA8,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xA9,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xAA,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xAB,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xAC,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xAD,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xAE,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xAF,
        bytes: 1,
        cycles: 4,
    },
    // 0xB0-0xBF
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xB0,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xB1,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xB2,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xB3,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xB4,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xB5,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xB6,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xB7,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xB8,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xB9,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xBA,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xBB,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xBC,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xBD,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xBE,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xBF,
        bytes: 1,
        cycles: 4,
    },
    // 0xC0-0xCF
    InstructionMeta {
        mnemonic: "RET",
        opcode: 0xC0,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "POP",
        opcode: 0xC1,
        bytes: 1,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "JP",
        opcode: 0xC2,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "JP",
        opcode: 0xC3,
        bytes: 3,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "CALL",
        opcode: 0xC4,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "PUSH",
        opcode: 0xC5,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0xC6,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RST",
        opcode: 0xC7,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RET",
        opcode: 0xC8,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RET",
        opcode: 0xC9,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "JP",
        opcode: 0xCA,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "PREFIX",
        opcode: 0xCB,
        bytes: 1,
        cycles: 0,
    },
    InstructionMeta {
        mnemonic: "CALL",
        opcode: 0xCC,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "CALL",
        opcode: 0xCD,
        bytes: 3,
        cycles: 24,
    },
    InstructionMeta {
        mnemonic: "ADC",
        opcode: 0xCE,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RST",
        opcode: 0xCF,
        bytes: 1,
        cycles: 16,
    },
    // 0xD0-0xDF
    InstructionMeta {
        mnemonic: "RET",
        opcode: 0xD0,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "POP",
        opcode: 0xD1,
        bytes: 1,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "JP",
        opcode: 0xD2,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_D3",
        opcode: 0xD3,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CALL",
        opcode: 0xD4,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "PUSH",
        opcode: 0xD5,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SUB",
        opcode: 0xD6,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RST",
        opcode: 0xD7,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RET",
        opcode: 0xD8,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RETI",
        opcode: 0xD9,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "JP",
        opcode: 0xDA,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_DB",
        opcode: 0xDB,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CALL",
        opcode: 0xDC,
        bytes: 3,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_DD",
        opcode: 0xDD,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "SBC",
        opcode: 0xDE,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RST",
        opcode: 0xDF,
        bytes: 1,
        cycles: 16,
    },
    // 0xE0-0xEF
    InstructionMeta {
        mnemonic: "LDH",
        opcode: 0xE0,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "POP",
        opcode: 0xE1,
        bytes: 1,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "LDH",
        opcode: 0xE2,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_E3",
        opcode: 0xE3,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_E4",
        opcode: 0xE4,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "PUSH",
        opcode: 0xE5,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "AND",
        opcode: 0xE6,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RST",
        opcode: 0xE7,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "ADD",
        opcode: 0xE8,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "JP",
        opcode: 0xE9,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0xEA,
        bytes: 3,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_EB",
        opcode: 0xEB,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_EC",
        opcode: 0xEC,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_ED",
        opcode: 0xED,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "XOR",
        opcode: 0xEE,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RST",
        opcode: 0xEF,
        bytes: 1,
        cycles: 16,
    },
    // 0xF0-0xFF
    InstructionMeta {
        mnemonic: "LDH",
        opcode: 0xF0,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "POP",
        opcode: 0xF1,
        bytes: 1,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "LDH",
        opcode: 0xF2,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "DI",
        opcode: 0xF3,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_F4",
        opcode: 0xF4,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "PUSH",
        opcode: 0xF5,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "OR",
        opcode: 0xF6,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RST",
        opcode: 0xF7,
        bytes: 1,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0xF8,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0xF9,
        bytes: 1,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "LD",
        opcode: 0xFA,
        bytes: 3,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "EI",
        opcode: 0xFB,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_FC",
        opcode: 0xFC,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "ILLEGAL_FD",
        opcode: 0xFD,
        bytes: 1,
        cycles: 4,
    },
    InstructionMeta {
        mnemonic: "CP",
        opcode: 0xFE,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RST",
        opcode: 0xFF,
        bytes: 1,
        cycles: 16,
    },
];

pub const CBPREFIXED_INSTRUCTIONS: [InstructionMeta; 256] = [
    // 0x00-0x0F
    InstructionMeta {
        mnemonic: "RLC",
        opcode: 0x00,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RLC",
        opcode: 0x01,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RLC",
        opcode: 0x02,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RLC",
        opcode: 0x03,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RLC",
        opcode: 0x04,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RLC",
        opcode: 0x05,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RLC",
        opcode: 0x06,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RLC",
        opcode: 0x07,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRC",
        opcode: 0x08,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRC",
        opcode: 0x09,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRC",
        opcode: 0x0A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRC",
        opcode: 0x0B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRC",
        opcode: 0x0C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRC",
        opcode: 0x0D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RRC",
        opcode: 0x0E,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RRC",
        opcode: 0x0F,
        bytes: 2,
        cycles: 8,
    },
    // 0x10-0x1F
    InstructionMeta {
        mnemonic: "RL",
        opcode: 0x10,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RL",
        opcode: 0x11,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RL",
        opcode: 0x12,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RL",
        opcode: 0x13,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RL",
        opcode: 0x14,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RL",
        opcode: 0x15,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RL",
        opcode: 0x16,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RL",
        opcode: 0x17,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RR",
        opcode: 0x18,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RR",
        opcode: 0x19,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RR",
        opcode: 0x1A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RR",
        opcode: 0x1B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RR",
        opcode: 0x1C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RR",
        opcode: 0x1D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RR",
        opcode: 0x1E,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RR",
        opcode: 0x1F,
        bytes: 2,
        cycles: 8,
    },
    // 0x20-0x2F
    InstructionMeta {
        mnemonic: "SLA",
        opcode: 0x20,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SLA",
        opcode: 0x21,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SLA",
        opcode: 0x22,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SLA",
        opcode: 0x23,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SLA",
        opcode: 0x24,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SLA",
        opcode: 0x25,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SLA",
        opcode: 0x26,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SLA",
        opcode: 0x27,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRA",
        opcode: 0x28,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRA",
        opcode: 0x29,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRA",
        opcode: 0x2A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRA",
        opcode: 0x2B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRA",
        opcode: 0x2C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRA",
        opcode: 0x2D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRA",
        opcode: 0x2E,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SRA",
        opcode: 0x2F,
        bytes: 2,
        cycles: 8,
    },
    // 0x30-0x3F
    InstructionMeta {
        mnemonic: "SWAP",
        opcode: 0x30,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SWAP",
        opcode: 0x31,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SWAP",
        opcode: 0x32,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SWAP",
        opcode: 0x33,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SWAP",
        opcode: 0x34,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SWAP",
        opcode: 0x35,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SWAP",
        opcode: 0x36,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SWAP",
        opcode: 0x37,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRL",
        opcode: 0x38,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRL",
        opcode: 0x39,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRL",
        opcode: 0x3A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRL",
        opcode: 0x3B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRL",
        opcode: 0x3C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRL",
        opcode: 0x3D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SRL",
        opcode: 0x3E,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SRL",
        opcode: 0x3F,
        bytes: 2,
        cycles: 8,
    },
    // 0x40-0x4F
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x40,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x41,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x42,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x43,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x44,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x45,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x46,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x47,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x48,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x49,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x4A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x4B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x4C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x4D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x4E,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x4F,
        bytes: 2,
        cycles: 8,
    },
    // 0x50-0x5F
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x50,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x51,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x52,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x53,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x54,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x55,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x56,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x57,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x58,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x59,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x5A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x5B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x5C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x5D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x5E,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x5F,
        bytes: 2,
        cycles: 8,
    },
    // 0x60-0x6F
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x60,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x61,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x62,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x63,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x64,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x65,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x66,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x67,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x68,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x69,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x6A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x6B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x6C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x6D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x6E,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x6F,
        bytes: 2,
        cycles: 8,
    },
    // 0x70-0x7F
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x70,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x71,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x72,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x73,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x74,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x75,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x76,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x77,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x78,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x79,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x7A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x7B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x7C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x7D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x7E,
        bytes: 2,
        cycles: 12,
    },
    InstructionMeta {
        mnemonic: "BIT",
        opcode: 0x7F,
        bytes: 2,
        cycles: 8,
    },
    // 0x80-0x8F
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x80,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x81,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x82,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x83,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x84,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x85,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x86,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x87,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x88,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x89,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x8A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x8B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x8C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x8D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x8E,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x8F,
        bytes: 2,
        cycles: 8,
    },
    // 0x90-0x9F
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x90,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x91,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x92,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x93,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x94,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x95,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x96,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x97,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x98,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x99,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x9A,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x9B,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x9C,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x9D,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x9E,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0x9F,
        bytes: 2,
        cycles: 8,
    },
    // 0xA0-0xAF
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA0,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA1,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA2,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA3,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA4,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA5,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA6,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA7,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA8,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xA9,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xAA,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xAB,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xAC,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xAD,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xAE,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xAF,
        bytes: 2,
        cycles: 8,
    },
    // 0xB0-0xBF
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB0,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB1,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB2,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB3,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB4,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB5,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB6,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB7,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB8,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xB9,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xBA,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xBB,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xBC,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xBD,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xBE,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "RES",
        opcode: 0xBF,
        bytes: 2,
        cycles: 8,
    },
    // 0xC0-0xCF
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC0,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC1,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC2,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC3,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC4,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC5,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC6,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC7,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC8,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xC9,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xCA,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xCB,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xCC,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xCD,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xCE,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xCF,
        bytes: 2,
        cycles: 8,
    },
    // 0xD0-0xDF
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD0,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD1,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD2,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD3,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD4,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD5,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD6,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD7,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD8,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xD9,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xDA,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xDB,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xDC,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xDD,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xDE,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xDF,
        bytes: 2,
        cycles: 8,
    },
    // 0xE0-0xEF
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE0,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE1,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE2,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE3,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE4,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE5,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE6,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE7,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE8,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xE9,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xEA,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xEB,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xEC,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xED,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xEE,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xEF,
        bytes: 2,
        cycles: 8,
    },
    // 0xF0-0xFF
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF0,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF1,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF2,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF3,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF4,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF5,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF6,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF7,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF8,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xF9,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xFA,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xFB,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xFC,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xFD,
        bytes: 2,
        cycles: 8,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xFE,
        bytes: 2,
        cycles: 16,
    },
    InstructionMeta {
        mnemonic: "SET",
        opcode: 0xFF,
        bytes: 2,
        cycles: 8,
    },
];
